### ISSUE TITLE
Heatlayer radius over 80 creates strange object outside default heat

### ISSUE THREAD

**Issue by zfky-dev** [Leaflet/Leaflet.heat#108]
If I create heatlayer with radius over 80 it creates valid heatmap but outside that circle, something strange appears.

Code:

`    
var heat = L.heatLayer([], {
        radius: 80,
        minOpacity: .6,
        opacity: 0.8,
        blur: 100,
        gradient: {
            1.0: color,
        },
    });
    heat.addTo(mymap);
`

![screen](https://user-images.githubusercontent.com/9828438/54017733-36f61c80-4187-11e9-9a7d-02046b9a6a7b.PNG)

It seems that bigger radius than some value is creating second object(?) outside default heat circle.

**Comment by corrigancd** [comment]
Have replicated this (top image). When I zoom out, it's fine. The parameters required to make each map are also specified: 
![image](https://user-images.githubusercontent.com/36197976/72535740-f2401500-3870-11ea-9696-47a145f3dd3a.png)

**Comment by mpraus** [comment]
This doesn't only happen when the radius is over 80. I have the same issue with a higher blur value. As far as I can tell it  only happens when the blur value is greater than or equal to the radius with the size of the object increases with the blur value.

Code to reproduce issue:
```
 heatLayer = L.heatLayer(heatdata, {radius: 75,  gradient: gradient, blur: 80, maxZoom:18});
 heatLayer.addTo(map);
```

![image](https://github.com/Leaflet/Leaflet.heat/assets/35736688/a364712f-bb0f-4072-b9f9-608655dd5a3d)

As far as I can tell your issue isn't really a radius of 80 but rather that the blur level is too high. It does appear to become problematic with a radius over about 100, regardless of the blur value. I believe it has something to do with the fact that a large number of points end up overlapping.

**Comment by jxn-30** [comment]
As a workaround: Import [simpleheat](https://github.com/mourner/simpleheat/tags) `0.3.0` or later **after** importing `Leaflet.heat`.

`Leaflet.heat` includes a `simpleheat` version from 2014: https://github.com/Leaflet/Leaflet.heat/blob/fbca30069de2b8416be8c63110e5d258579e3169/dist/leaflet-heat.js#L1-L5

The issue has been resolved in `simpleheat` in 2015: https://github.com/mourner/simpleheat/issues/14, [Version 0.3.0](https://github.com/mourner/simpleheat/releases/tag/v0.3.0) has been released afterwards.

Using TypeScript and Webpack, we achieved this workaround: https://github.com/LSS-Manager/LSSM-V.4/commit/7d07baa219a70b60fb2d41433500994c7e5f5819 importing `Leaflet.heat` first, then `simpleheat` and afterwards we've assigned the imported `simpleheat` to the global scope.

**Comment by Sergiobop** [comment]
Hi @jxn-30 is a release possible with this fix included? Thanks

**Comment by jxn-30** [comment]
> Hi @jxn-30 is a release possible with this fix included? Thanks

I am not a maintainer of this project, so I am not in the power to do so. However, there already exists an Issue that also requests a new release: #132

**Comment by Sergiobop** [comment]
Oh, ok, thank you anyway. I guess @IvanSanchez can do the new release?

> > Hi @jxn-30 is a release possible with this fix included? Thanks
> 
> I am not a maintainer of this project, so I am not in the power to do so. However, there already exists an Issue that also requests a new release: #132
